name: fashion3d_project
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  # Python and base
  - python=3.9
  - pip

  # TensorFlow with GPU for RTX 2000 Ada
  - tensorflow-gpu=2.13.0
  - cudatoolkit=11.8
  - cudnn=8.6.0

  # Image and 3D processing
  - opencv=4.8.0
  - pillow=10.0.0
  - scikit-image=0.21.0
  - trimesh=3.23.5
  - open3d=0.17.0

  # Scientific computing
  - numpy=1.24.3
  - scipy=1.11.1
  - matplotlib=3.7.2
  - seaborn=0.12.2

  # Utilities
  - tqdm=4.65.0
  - pyyaml=6.0
  - h5py=3.9.0

  # API
  - fastapi=0.103.0
  - uvicorn=0.23.2
  - python-multipart=0.0.6

  # Jupyter for development
  - jupyter=1.0.0
  - ipykernel=6.25.0

  # Via pip
  - pip:
    # 3D specialized generation
    - point-cloud-utils==0.29.7
    - pymeshlab==2022.2.post4
    - mcubes==0.1.0
    
    # 3D visualization
    - plotly==5.16.1
    - pyvista==0.42.3
    
    # Monitoring and logging
    - tensorboard==2.13.0
    - wandb==0.15.8
    
    # Memory optimization
    - memory-profiler==0.61.0
    
    # Data augmentation
    - albumentations==1.3.1
    
    # 3D metrics
    - pytorch3d  # For 3D distance metrics
    
    # Additional utilities
    - rich==13.5.2  # Elegant CLI interface
    - typer==0.9.0  # CLI framework
